name: Publish Docker image

on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  push_to_registries:
    name: Push Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_TOKEN }}
      - name: Log in to the Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/OksanaDemidovec/docker_build:1

      - name: Slack notifications
        uses: rtCamp/action-slack-notify@v2
        if: success()
        env:
          SLACK_CHANNEL: notification_github
          SLACK_COLOR: 'green'
          SLACK_ICON: <https://github.com/rtCamp.png?size=48>
          SLACK_MESSAGE: 'Pushing build_docker:${{ github.ref_name }} image is SUCCESS'
          SLACK_TITLE: Post build docker image
          SLACK_USERNAME: git_md-sa2-23-23
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - name: Slack FAIL notification
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_CHANNEL: notification_github
          SLACK_COLOR: 'red'
          SLACK_ICON: <https://github.com/rtCamp.png?size=48>
          SLACK_MESSAGE: 'Pushing build_docker:${{ github.ref_name }} image is FAIL'
          SLACK_TITLE: Failed build docker image
          SLACK_USERNAME: git_md-sa2-23-23
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
