name: Check remote host and push report

on:
  push:
  
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Get branches with changes
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.push.head.ref }}
        
      - name: Find tabs
        run: |
          #!/bin/bash

          # Получить список всех веток
          branches=$(git branch -a | sed 's/^..//' | grep -v HEAD)

          # Для каждой ветки выполнить проверку
          for branch in $branches; do
            # Переключиться на ветку
            git checkout $branch &> /dev/null
    
            # Получить список измененных файлов в ветке
            files=$(git diff --name-only HEAD)

            # Использовать команду grep для поиска табуляций в каждом файле
            grep_output=$(echo "$files" | xargs grep -n $'\t')

            # Вывести количество табуляций в каждом файле
            echo "Количество табуляций в ветке $branch:"
            echo "$grep_output"

            # Обработать вывод, чтобы получить общее количество табуляций
            total_count=$(echo "$grep_output" | awk -F ':' '{sum += $2} END {print sum}')
            echo "Общее количество табуляций в ветке $branch: $total_count"
          done

          # Вернуться на главную ветку
          git checkout main &> /dev/null

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: nc_report.log
          path: nc_report.log
